Repository team-inplace/inplace, pull requests merged in 2025-09, with the labels that each got.

#389 [INPLACE-292] alarm refactoring
  backend/inplace-api/src/main/java/my/inplace/api/alarm/AlarmController.java
  backend/inplace-api/src/main/java/my/inplace/api/alarm/dto/AlarmResponse.java
  backend/inplace-api/src/main/java/my/inplace/api/user/UserController.java
  backend/inplace-api/src/main/java/my/inplace/api/user/UserControllerApiSpec.java
  backend/inplace-api/src/main/java/my/inplace/api/user/dto/UserRequest.java
  backend/inplace-application/src/main/java/my/inplace/application/alarm/command/AlarmCommandFacade.java
  backend/inplace-application/src/main/java/my/inplace/application/alarm/command/AlarmCommandService.java
  backend/inplace-application/src/main/java/my/inplace/application/alarm/event/AlarmEventHandler.java
  backend/inplace-application/src/main/java/my/inplace/application/alarm/query/dto/AlarmResult.java
  backend/inplace-application/src/main/java/my/inplace/application/post/command/PostCommandFacade.java
  backend/inplace-application/src/main/java/my/inplace/application/post/query/PostQueryService.java
  backend/inplace-application/src/main/java/my/inplace/application/user/UserFacade.java
  backend/inplace-application/src/main/java/my/inplace/application/user/command/UserCommandService.java
  backend/inplace-application/src/main/java/my/inplace/application/user/query/UserQueryService.java
  backend/inplace-domain/src/main/java/my/inplace/domain/alarm/Alarm.java
  backend/inplace-domain/src/main/java/my/inplace/domain/alarm/AlarmComment.java
  backend/inplace-domain/src/main/java/my/inplace/domain/user/User.java
  backend/inplace-infra/src/main/java/my/inplace/infra/post/jpa/PostJpaRepository.java
Labels: refactor

#391 [INPLACE-297] Comment 작성 오류 수정
  backend/build.gradle
  backend/inplace-application/src/main/java/my/inplace/application/user/command/UserCommandService.java
Labels: enhancement

#390 ReadQuerydslRepository Test
  .github/workflows/branch-name.yml
  backend/inplace-api/src/main/java/my/inplace/api/place/dto/PlaceRequest.java
  backend/inplace-application/src/main/java/my/inplace/application/place/query/dto/PlaceParam.java
  backend/inplace-application/src/main/java/my/inplace/application/review/dto/ReviewResult.java
  backend/inplace-application/src/main/java/my/inplace/application/video/query/VideoQueryService.java
  backend/inplace-application/src/main/java/my/inplace/application/video/query/dto/VideoParam.java
  backend/inplace-domain/src/main/java/my/inplace/domain/place/query/PlaceQueryParam.java
  backend/inplace-domain/src/main/java/my/inplace/domain/review/Review.java
  backend/inplace-domain/src/main/java/my/inplace/domain/review/query/ReviewQueryResult.java
  backend/inplace-domain/src/main/java/my/inplace/domain/video/query/VideoQueryParam.java
  backend/inplace-domain/src/main/java/my/inplace/domain/video/query/VideoReadRepository.java
  backend/inplace-infra/build.gradle
  backend/inplace-infra/src/main/java/my/inplace/infra/place/PlaceReadQueryDslRepository.java
  backend/inplace-infra/src/main/java/my/inplace/infra/post/CommentReadQueryDslRepository.java
  backend/inplace-infra/src/main/java/my/inplace/infra/post/PostReadQueryDslRepository.java
  backend/inplace-infra/src/main/java/my/inplace/infra/review/ReviewReadQueryDslRepository.java
  backend/inplace-infra/src/main/java/my/inplace/infra/video/VideoReadQueryDslRepository.java
  backend/inplace-infra/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
  backend/inplace-infra/src/test/java/my/inplace/infra/TestApplication.java
  backend/inplace-infra/src/test/java/my/inplace/infra/config/AbstractMySQLContainer.java
  backend/inplace-infra/src/test/java/my/inplace/infra/config/TestQueryDslConfig.java
  backend/inplace-infra/src/test/java/my/inplace/infra/influencer/InfluencerReadQueryDslRepositoryTest.java
  backend/inplace-infra/src/test/java/my/inplace/infra/place/PlaceReadQueryDslRepositoryTest.java
  backend/inplace-infra/src/test/java/my/inplace/infra/post/CommentReadQueryDslRepositoryTest.java
  backend/inplace-infra/src/test/java/my/inplace/infra/post/PostReadQueryDslRepositoryTest.java
  backend/inplace-infra/src/test/java/my/inplace/infra/review/ReviewReadQueryDslRepositoryTest.java
  backend/inplace-infra/src/test/java/my/inplace/infra/search/InfluencerSearchQueryDslRepositoryTest.java
  backend/inplace-infra/src/test/java/my/inplace/infra/search/PlaceSearchQueryDslRepositoryTest.java
  backend/inplace-infra/src/test/java/my/inplace/infra/search/VideoSearchQueryDslRepositoryTest.java
  backend/inplace-infra/src/test/java/my/inplace/infra/user/UserReadQueryDslRepositoryTest.java
  backend/inplace-infra/src/test/java/my/inplace/infra/video/VideoReadQueryDslRepositoryTest.java
  backend/inplace-infra/src/test/resources/application-test-mysql.yaml
  backend/inplace-infra/src/test/resources/application-test.yaml
  backend/inplace-infra/src/test/resources/sql/test-influencer.sql
  backend/inplace-infra/src/test/resources/sql/test-place.sql
  backend/inplace-infra/src/test/resources/sql/test-post.sql
  backend/inplace-infra/src/test/resources/sql/test-review.sql
  backend/inplace-infra/src/test/resources/sql/test-search-influencer.sql
  backend/inplace-infra/src/test/resources/sql/test-search-place.sql
  backend/inplace-infra/src/test/resources/sql/test-search-video.sql
  backend/inplace-infra/src/test/resources/sql/test-user.sql
  backend/inplace-infra/src/test/resources/sql/test-video.sql
Labels: test
