Repository team-inplace/inplace, pull requests merged in 2025-01, with the labels that each got.

#52 [INPLACE-62] Local Cors 설정 추가
  backend/src/main/java/team7/inplace/security/config/CorsConfig.java
Labels: bug

#62 [INPLACE-71] Liked 패키지로 통일하고 하위 패키지를 설정해요
  backend/src/main/java/team7/inplace/influencer/application/InfluencerService.java
  backend/src/main/java/team7/inplace/liked/likedInfluencer/application/FavoriteInfluencerService.java
  backend/src/main/java/team7/inplace/liked/likedInfluencer/application/dto/FavoriteInfluencerCommand.java
  backend/src/main/java/team7/inplace/liked/likedInfluencer/application/dto/FavoriteInfluencerListCommand.java
  backend/src/main/java/team7/inplace/liked/likedInfluencer/domain/FavoriteInfluencer.java
  backend/src/main/java/team7/inplace/liked/likedInfluencer/persistent/FavoriteInfluencerRepository.java
  backend/src/main/java/team7/inplace/liked/likedInfluencer/presentation/FavoriteInfluencerController.java
  backend/src/main/java/team7/inplace/liked/likedInfluencer/presentation/FavoriteInfluencerControllerApiSpec.java
  backend/src/main/java/team7/inplace/liked/likedInfluencer/presentation/dto/InfluencerLikeRequest.java
  backend/src/main/java/team7/inplace/liked/likedInfluencer/presentation/dto/InfluencerListLikeRequest.java
  backend/src/main/java/team7/inplace/liked/likedPlace/domain/LikedPlace.java
  backend/src/main/java/team7/inplace/liked/likedPlace/persistence/LikedPlaceRepository.java
  backend/src/main/java/team7/inplace/place/application/PlaceService.java
  backend/src/main/java/team7/inplace/place/application/dto/LikedPlaceInfo.java
  backend/src/main/java/team7/inplace/search/application/SearchService.java
  backend/src/main/java/team7/inplace/user/application/UserFacade.java
  backend/src/main/java/team7/inplace/user/application/UserService.java
  backend/src/main/java/team7/inplace/video/application/VideoFacade.java
  backend/src/test/java/team7/inplace/influencer/InfluencerServiceTest.java
  backend/src/test/java/team7/inplace/likedInfluencer/FavoriteInfluencerServiceTest.java
  backend/src/test/java/team7/inplace/likedPlace/persistence/LikedPlaceRepositoryTest.java
  backend/src/test/java/team7/inplace/place/application/PlaceServiceTest.java
Labels: documentation

#53 [INPLACE-61] 로그인 없이 리뷰 등록
  backend/src/main/java/team7/inplace/InplaceApplication.java
  backend/src/main/java/team7/inplace/global/exception/code/ReviewErrorCode.java
  backend/src/main/java/team7/inplace/place/presentation/PlaceController.java
  backend/src/main/java/team7/inplace/place/presentation/PlaceControllerApiSpec.java
  backend/src/main/java/team7/inplace/placeMessage/application/KakaoMessageService.java
  backend/src/main/java/team7/inplace/placeMessage/application/PlaceMessageFacade.java
  backend/src/main/java/team7/inplace/placeMessage/application/UserReviewUuidService.java
  backend/src/main/java/team7/inplace/placeMessage/domain/UserReviewUuid.java
  backend/src/main/java/team7/inplace/placeMessage/persistence/UserReviewUuidRepository.java
  backend/src/main/java/team7/inplace/placeMessage/util/FeedTemplate.java
  backend/src/main/java/team7/inplace/placeMessage/util/KakaoMessageMaker.java
  backend/src/main/java/team7/inplace/review/application/ReviewService.java
  backend/src/main/java/team7/inplace/security/config/RedisConfig.java
  backend/src/test/java/team7/inplace/review/ReviewServiceTest.java
Labels: enhancement

#64 [INPLACE-72] baseEntity 사용 설정 및 구성
  backend/src/main/java/team7/inplace/InplaceApplication.java
  backend/src/main/java/team7/inplace/global/baseEntity/BaseEntity.java
Labels: enhancement

#92 [INPLACE-25] 어드민 로그인
  backend/src/main/java/team7/inplace/admin/AdminPageController.java
  backend/src/main/java/team7/inplace/admin/user/application/AdminUserService.java
  backend/src/main/java/team7/inplace/admin/user/application/command/RegisterCommand.java
  backend/src/main/java/team7/inplace/admin/user/application/dto/AdminUserInfo.java
  backend/src/main/java/team7/inplace/admin/user/domain/AdminUser.java
  backend/src/main/java/team7/inplace/admin/user/persistence/AdminUserRepository.java
  backend/src/main/java/team7/inplace/admin/user/presentation/AdminLoginController.java
  backend/src/main/java/team7/inplace/admin/user/presentation/dto/LoginRequest.java
  backend/src/main/java/team7/inplace/security/application/CustomUserDetailsService.java
  backend/src/main/java/team7/inplace/security/application/dto/CustomUserDetails.java
  backend/src/main/java/team7/inplace/security/config/SecurityConfig.java
  backend/src/main/java/team7/inplace/security/config/SecurityEntryPointConfig.java
  backend/src/main/java/team7/inplace/security/config/SecurityServiceConfig.java
  backend/src/main/java/team7/inplace/security/config/SecurityUtilConfig.java
  backend/src/main/java/team7/inplace/security/entryPoint/LoginAuthenticationEntryPoint.java
  backend/src/main/java/team7/inplace/security/handler/CustomSuccessHandler.java
  backend/src/main/java/team7/inplace/security/util/CookieUtil.java
  backend/src/main/java/team7/inplace/token/presentation/RefreshTokenController.java
  backend/src/main/java/team7/inplace/user/application/UserService.java
  backend/src/main/java/team7/inplace/user/application/dto/UserCommand.java
  backend/src/main/java/team7/inplace/user/persistence/UserRepository.java
  backend/src/main/resources/application-db.yaml
  backend/src/main/resources/application.yaml
  backend/src/main/resources/templates/admin/login.html
  backend/src/main/resources/templates/admin/main.html
Labels: enhancement

#98 [INPLACE-93] hotfix - 쿠키 key (ACCESS_TOKEN => access_token)
  backend/src/main/java/team7/inplace/security/handler/CustomSuccessHandler.java
Labels: bug

#106 [INPLACE-93] 어드민유저가 장소를 등록할때 카테고리도 정해줘야함.
  backend/src/main/java/team7/inplace/admin/crawling/application/CrawlingFacade.java
  backend/src/main/java/team7/inplace/admin/crawling/application/command/PlaceRegistrationCommand.java
  backend/src/main/java/team7/inplace/admin/crawling/presentation/CrawlingController.java
  backend/src/main/java/team7/inplace/admin/crawling/presentation/dto/PlaceRegistrationRequest.java
  backend/src/main/java/team7/inplace/place/application/command/PlacesCommand.java
  backend/src/main/resources/static/css/login.css
  backend/src/main/resources/static/css/style.css
  backend/src/main/resources/static/js/video.js
  backend/src/main/resources/templates/admin/login.html
  backend/src/main/resources/templates/admin/video.html
Labels: enhancement

#99 [INPLACE-103] 인플루언서의 비디오 정보 반환 API 구현
  backend/src/main/java/team7/inplace/video/application/VideoService.java
  backend/src/main/java/team7/inplace/video/domain/Video.java
  backend/src/main/java/team7/inplace/video/persistence/VideoReadRepository.java
  backend/src/main/java/team7/inplace/video/persistence/VideoReadRepositoryImpl.java
  backend/src/main/java/team7/inplace/video/persistence/VideoRepository.java
  backend/src/main/java/team7/inplace/video/persistence/dto/VideoQueryResult.java
  backend/src/main/java/team7/inplace/video/presentation/VideoController.java
  backend/src/main/java/team7/inplace/video/presentation/VideoControllerApiSpec.java
Labels: enhancement
